/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ae836bd8-4fc6-4565-ba1d-d89a6467fcea",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_JTvQZhe8H",
    "aws_user_pools_web_client_id": "7d09p3nrooqggejsvbrvsdjvdv",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "residential-payments-storage123b2-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
